config/routes.rb
HITWebsite::Application.routes.draw do
  resources :products

  get "home/index"
  get 'about' => 'home#about'
  get 'all' => 'products#all'
  

   root 'home#index'

   resources :products do 
    resources :images
   end
     
  
   resources :contacts, only: [:index, :create]
   
   resource :admin_session

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  acts_as_authentic  
end

app/models/admin_session.rb
class AdminSession < Authlogic::Session::Base
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone
  attribute :message, :validate => true
  attribute :nickname,  :captcha  => true, :format => { :with => /^$/ }

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "HIT Inquiry from Website",
      :to => [ "cauhaus2040@gmail.com", "teresatarn@gmail.com" ],
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :images, :dependent => :destroy
  accepts_nested_attributes_for :images, :allow_destroy => true, reject_if: :all_blank
 
  #validates :image, :presence => true
end

app/controllers/admin_sessions_controller.rb
class AdminSessionsController < ApplicationController  
  
  before_filter :require_user, :only => :destroy
    
  def new
    @admin_session = AdminSession.new
  end

  def create
    @admin_session = AdminSession.new(params[:admin_session])
    if @admin_session.save
      flash[:notice] = "Login successful!"
      redirect_to products_path
    else
      flash[:notice] = "Not successfully saved."
      render :action => :new
    end
  end

  def destroy
    current_admin_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_to products_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper :all # include all helpers, all the time  
  protect_from_forgery with: :exception
  
  layout "application"
    
    helper_method :current_admin_session, :current_admin  
  
    private  
    def current_admin_session  
      return @current_admin_session if defined?(@current_admin_session)  
      @current_admin_session = AdminSession.find  
    end  
  
    def current_admin  
      return @current_admin if defined?(@current_admin)  
      @current_admin = current_admin_session && current_admin_session.user  
    end  
    
    def require_user
      logger.debug "ApplicationController::require_user"
      unless current_admin
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_admin_session_url
        return false
      end
    end
    
    def store_location
          session[:return_to] = request.url
        end
    
        
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = 'Cannot send message.'
      
    end
    render :index
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
#    render "about"
  end
  
  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :get_products, only: [:index, :show, :all]
  #before_action :require_user, except: [:index, :show]

  # GET /products
  # GET /products.json
  def index
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/all
  def all
  end
  
  # GET /products/new
  def new
    @product = Product.new
    @product.images.build
  end

  # GET /products/1/edit
  def edit
    
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end
    
    def get_products 
      @products = Product.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, images_attributes: [:imageURL, :product_id, :id, :title])
    end
 
end

app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    return markdown.render(text).html_safe
  end
   
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "URL_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin_sessions/new.html.erb
<%= provide(:title, 'Admin Login')%>
  
<%= form_for @admin_session, :url => admin_session_path do |f| %>
  <p>  
    <%= f.label :login %><br />  
    <%= f.text_field :login %>  
  </p>  
  
  <p>  
    <%= f.label :password %><br />  
    <%= f.password_field :password %>  
  </p>  
  
  <%= f.submit "Login" %>  
<% end %>  

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

app/views/contacts/_newContact.html.erb
<div id="contactFormTitle">
	<h3>Contact Form</h3> 
	<div id="requiredLabel">( * = required )</div>
</div>

<%= simple_form_for @contact do |f| %>
	<div>
		<%= f.input :name, :input_html => { :class => 'formField'}  %>
	</div>
	<div>
	<%= f.input :email, :input_html => { :class => 'formField'}  %>
</div>
	<div>
	<%= f.input :phone, :input_html => { :class => 'formField'}  %>
</div>
<div>
	<%= f.input :message, :as => :text, :input_html => { :rows => 10, :class => 'formField'} %>
</div>
	<div style="display: none">
		<%= f.input :nickname %>
	</div>
	<div>
		<%= f.submit "Send", :id => 'contactFormBtn' %>
	</div>
<% end %>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/index.html.erb
<%= provide(:title, 'Contact')%>
<div id='contactBanner' class="banner">
	<div id='contactTitle' class="bannerTitle">
		<h1>Contact Holo Image Technology (HIT)</h1>
	</div>
</div>

<div id='contactLeft'>
    <div id="contactInfo">
		<h3>Details</h3>
	           <p><b>Holo Image Technology</b><br />
	   101 William Leigh Drive<br />
	   Tullytown, PA 19007 USA<br /></p>

	   <div class="contactTable">
		  <table class="tableData">
			  <tr>
			  	<td>Phone: 	</td><td>	+1 (215) 946-2190</td>
			  </tr>
				<tr>
			  	<td>Fax: 	</td><td>	+1 (215) 946-2129</td>
			  </tr>
			  <tr>
					<td>Skype: 	</td><td>	holochiang </td>
				</tr>
			  <tr>
					<td>E-mail: </td><td>	<a href="mailto:info&#64holoimagetechnology.com">info@holoimagetechnology.com</a><br/></td>
				</tr>
				<tr>
					<td>Attn:</td><td>	 Tom Chiang</td>
			  </tr>
			  <br />
		  </table>
			</br>
	   </div>
	</div>

</div>
	<!-- end #contactLeft -->

<div id='contactRight'>
    <div id="contactForm">
		<div id="contactMap">
	        <div id="googlemap">
	        	<iframe width="375" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=101+William+Leigh+Dr,+Tullytown,+PA+19007&amp;sll=37.0625,-95.677068&amp;sspn=34.313287,49.482422&amp;ie=UTF8&amp;hq=&amp;hnear=101+William+Leigh+Dr,+Tullytown,+Bucks,+Pennsylvania+19007&amp;ll=40.142756,-74.810584&amp;spn=0.129388,0.193291&amp;z=12&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=101+William+Leigh+Dr,+Tullytown,+PA+19007&amp;sll=37.0625,-95.677068&amp;sspn=34.313287,49.482422&amp;ie=UTF8&amp;hq=&amp;hnear=101+William+Leigh+Dr,+Tullytown,+Bucks,+Pennsylvania+19007&amp;ll=40.142756,-74.810584&amp;spn=0.129388,0.193291&amp;z=12" style="color:#0000FF;text-align:left">View Larger Map</a></small>
	        </div>
	        <br/></div></div>
		</div>
	</div>

</div>


<!-- -->

app/views/home/about.html.erb
<%= provide(:title, 'Welcome')%>
<div id='aboutBanner' class="banner">
	<div id='aboutTitle' class="bannerTitle">
		<h1>About Holo Image Technology (HIT)</h1>
	</div>
</div>

<div id='aboutContainer' class='contentContainer'>
<div id='aboutNav' class="contentNav">
	<ul>
		<li><%= link_to "Our Company", about_path %></li>
		<li><%= link_to "Partnerships", about_path(:anchor => "aboutClientsText") %></li>
		<li><%= link_to "Awards & Certifications", about_path(:anchor => "aboutAwardsText")%></li>
	</ul>
</div>

<div id='aboutContent' class="content">
	<div id='aboutCompanyText'>
	<h3>Company</h3>
		<p>Since 1992, HIT has been providing dedicated, one-on-one engineering expertise to clients from all over the world. HIT's contributions and leadership can be found in the research, design, and manufacturing of technologies for a wide variety of purposes, such as industrial grade assemblers, biomedical devices, consumer electronics, commercial pastry printers, and solar powered generators. </br> </br>The company pays close attention to each one of its clients to help them realize their goals more quickly and efficiently with sustainable economic savings. Helping clients achieve success through technical expertise and dedicated service stands as the ultimate goal of HIT.
		</p>
	</div> <!-- end #aboutCompanyText -->
	<hr />
	<div id="aboutClientsText">
		<h3>Partners & Clients</h3>
	    <p>The list below highlights the diversity of HIT's past partners and clients in regards to their size, location, and area of specialty. HIT prides itself on its enthusiasm and versatility to pursue and support research endeavors of any scale. For more details on any past projects or on how to collaborate with HIT in the future, please <a href="mailto:info@holoimagetechnology.com">contact us</a> today.</p>
	           <div class="lists">
	           	<h4><u>US</u></h4>
	           	<ul>
	                   <li><a href="http://www.kodak.com">Kodak CTP Research Department</a></li>
	                   <li><a href="http://www.rainbowcomputer.net/">Rainbow Computer Technology</a></li>
	                   <li><a href="http://www.simprnt.com/">Simprint</a></li>
	                   <li><a href="http://www.solarsmartsignage.com">SolarSmart</a></li>
	                   <li><a href="http://www.ezhitech.com">EZHiTech</a></li>
	                   <li><a href="http://www.syska.com">Syska</a></li>
	                   <li><a href="http://www.med.upenn.edu/bgs/">University of Pennsylvania Biomedical Department</a></li>
	                   <li><a href="http://www.fccc.edu">Fox Chase Cancer Center</a></li>
	               </ul>
	               <h4><u>Europe</u></h4>
	               <ul>
	               	<li>Manroland (Germany)</li>
	               	<li>Misomex International (Sweden)</li>
	                   </ul>
	               <h4><u>Asia</u></h4>
	               <ul>
	               	<li>Dalian Ceramic Technology (China)</li>
	                   <li>Golden Mold (Taiwan)</li>
	                   </ul>
	           </div>
	</div> <!-- end #aboutClientText -->
	<hr />
	<div id='aboutAwardsText'>
	<h3>Awards & Certification</h3>
	<div class="lists">
	        	<ul>
	            	<li>Certified Member of SPIE- The International Society for Optical Engineering
	                <li>Certified by SPIE in Interferometry and Modern Optical Testing
	            	<li>Photo Imaging Corporation Achievement Award for successful completion of the Photon Printer Integration</li>
	            </ul>
	        </div>
	
	</div> <!-- end #aboutCompanyText -->
	
</div> <!-- end #aboutContent -->
</div> <!-- end #aboutContainer -->

app/views/home/contact.html.erb
<div id='contactBanner' class="banner">
	<div id='contactTitle' class="bannerTitle">
		<h1>Contact Holo Image Technology (HIT)</h1>
	</div>
</div>

<div id='contactContainer'>
<div id='contactNav' class="contentNav">
	<ul>
		<li><a href="#contactInfo">Info</a></li>
		<li><a href="#contactMap">Map</a></li>
	</ul>
</div>

<div id='contactContent' class="content">
    <div id="contactInfo">
	<h3>Contact Information</h3>
           <hr />
           <p><b>Holo Image Technology</b><br />
   101 William Leigh Drive<br />
   Tullytown, PA 19007 USA<br /></p>

   <div class="contactTable">
		 <table class="tableData">
			 <tr>
				 <td>Phone: 	</td><td>	+1 (215) 946-2190</td>
			 </tr>
			 <tr>
				 <td>Fax: 	</td><td>	+1 (215) 946-2129</td>
			 </tr>
			 <tr>
				 <td>Skype: 	</td><td>	holochiang </td>
			 </tr>
			 <tr>
				 <td>E-mail: </td><td>	<a href="mailto:info&#64holoimagetechnology.com">info@holoimagetechnology.com</a><br/></td>
			 </tr>
			 <tr>
				 <td>Attn:</td><td>	 Tom Chiang</td>
			 </tr>
			 <br />
		 </table>
   </div>
</div>

<div id="contactForm">
	<%= render 'contacts/newContact' %>
</div>

   <div id="contactMap">
		   <h2>Map</h2>
           <hr />
           <div id="googlemap">
           	<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=101+William+Leigh+Dr,+Tullytown,+PA+19007&amp;sll=37.0625,-95.677068&amp;sspn=34.313287,49.482422&amp;ie=UTF8&amp;hq=&amp;hnear=101+William+Leigh+Dr,+Tullytown,+Bucks,+Pennsylvania+19007&amp;ll=40.142756,-74.810584&amp;spn=0.129388,0.193291&amp;z=12&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=101+William+Leigh+Dr,+Tullytown,+PA+19007&amp;sll=37.0625,-95.677068&amp;sspn=34.313287,49.482422&amp;ie=UTF8&amp;hq=&amp;hnear=101+William+Leigh+Dr,+Tullytown,+Bucks,+Pennsylvania+19007&amp;ll=40.142756,-74.810584&amp;spn=0.129388,0.193291&amp;z=12" style="color:#0000FF;text-align:left">View Larger Map</a></small>
               </div>
           <br/></div></div>
	   </div>


</div> <!-- end #aboutContent -->
<!-- -->

app/views/home/index.html.erb
<%= provide(:title, 'Welcome')%>
<div class="homeSlideshow">
	<ul class="slide">
		<li class="slideImage activeSlide" id="slide-1">
			<div class="image" id="ctpImage">
				
			</div>
			<div class="slideLabel" id="ctpLabel">
				<div class="slideLabelText">HIT delivers the highest quality CTP and optical system products and services fit for any task and budget.</div>
				<%= link_to product_path(:id => 2) do %><div class="slideLabelBtn">Learn More</div> <% end %>
			</div> <!-- End of slideLabel-->
		</li>
		
		<li class="slideImage" id="slide-2">
			<div class="image" id="solarImage">
				<%= image_tag 'solarLights.png' %>
				<div class="slideLabel" id="solarLabel">
					<div class="slideLabelText">Facilitate a sustainable future with HIT's original public infrastructure lighting solutions.</div>
					<%= link_to product_path(:id => 1) do %><div class="slideLabelBtn"><p>Learn More<p></div> <% end %>
				</div>
			</div>
			
		</li>
		
		<li class="slideImage" id="slide-3">
			<div class="image" id="opticsLab">
				<%= image_tag'opticsLab.png'%>
				<div class="slideLabel" id="opticsLabel">
					<div class="slideLabelText">Companies from all over the world have chosen to collaborate with HIT's state of the art laboratory and team of experts.</div>
					<%= link_to about_path(:anchor => "aboutClientsText") do %><div class="slideLabelBtn">Learn More</div> <% end %>
				</div>
			</div>
		</li>
		
		<li class="slideImage" id="slide-4">
			<div class="image" id="opticHead">
				<%= image_tag'opticHead.png'%>
				<div class="slideLabel" id="contactLabel">
					<div class="slideLabelText">Contact HIT now and receive world-class service and solutions for problems of all complexity.</div>
					<%= link_to contacts_path do %><div class="slideLabelBtn">Learn More</div> <% end %>
				</div>
			</div>
		</li>
	</ul>
</div>
<div class="homeInfoBar">
	<div class="homeInfoBox activeInfoBox" id="ctpInfoBox infoBox-1">
		<a href="">
		<div class="homeInfoBoxArrow">-</div>
		<div class="homeInfoBoxText">Delivering CTP and optical system expertise.</div>
		</a>
	</div>
	<div class="homeInfoBox" id="solarInfoBox infoBox-2">
		<a href="">
		<div class="homeInfoBoxArrow">-</div>
		<div class="homeInfoBoxText">Supporting a sustainable future.</div>
		</a>
	</div>
	<div class="homeInfoBox" id="partnersInfoBox infoBox-3">
		<a href="">
		<div class="homeInfoBoxArrow">-</div>
		<div class="homeInfoBoxText">Engaging with leaders across markets and industries.</div>
		</a>
	</div>
	<div class="homeInfoBox" id="contactInfoBox infoBox-4">
		<a href="">
		<div class="homeInfoBoxArrow">-</div>
		<div class="homeInfoBoxText">Adapting our services and products to our clients’ diverse needs. </div>
		</a>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<div id="footerContainer">
	<div id="copyrightInfo">
		<p>Copyright © 2014 Holo Image Technology. All rights reserved.</p>
	</div>
	<ul id="footerLinks">
			<li>
				<%= link_to "Home", home_index_path %>
			</li>
			<li>
				<%= link_to "About", about_path %>
			</li>
			<li>
				<%= link_to "Products", products_path %>
			</li>
			<li>
				<%= link_to "Contact", contacts_path%>
			</li>
	</ul>
</div>
</footer>

app/views/layouts/_header.html.erb
<header id="headerDiv">
<nav>
	<!-- <a href="../home/index.html">
		<div id="logo">	
		</div>
	</a> -->
		<%= link_to "", root_path, id: "logo" %>
	<ul id="topNav">
		<li class="navItem" id="home_btn">
			<%= link_to "HOME", home_index_path%>	
		</li>
		<li class="navItem" id="about_btn">
			<%= link_to "ABOUT", about_path %>
			<div class="navArrow">
				<%= image_tag "navArrow.png" %>
			</div>
			<ul class="sub">
				<li><%= link_to "Our Company", about_path %></li>
				<li><%= link_to "Partnerships", about_path(:anchor => "aboutClientsText") %></li>
				<li><%= link_to "Awards", about_path(:anchor => "aboutAwardsText")%></li>
			</ul>
		</li>
		<li class="navItem" id="products_btn">
			<%= link_to "PRODUCTS & SERVICES", products_path %>
			<div class="navArrow">
				<%= image_tag "navArrow.png" %>
			</div>
			<ul class="sub">
				<li><%= link_to "All Products", products_path %></li>
				<li><%= link_to "CTP Thermal Head", product_path(:id => 1) %></li>
				<li><%= link_to "HIT Plater 2230", product_path(:id => 2) %></li>
				<li><%= link_to "HIT Plater 2332", product_path(:id => 3)%></li>
				<li><%= link_to "Optical Laser System Repair", product_path(:id => 4)%></li>
				<li><%= link_to "Surface Inspector SI-1000", product_path(:id => 5)%></li>
				<li><%= link_to "HIT Solar Technology", product_path(:id => 6) %></li>
			</ul>
		</li>
		<li class="navItem" id='contact_btn' >
			<%= link_to "CONTACT", contacts_path %>
		</li>
	</ul>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HIT | Holo Image Technology: <%= yield(:title) %></title>
 
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  
   <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!--[if lt IE 9]> <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
</head>
<body>
	
	
		<%= render 'layouts/header' %>
	
	<div class="container">
		<%= yield %>
	</div> <!--End of container -->
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
</div>

    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description%>
  </div>
  <div id="images">
	  <%= f.fields_for :images do |builder| %>
	    <%= render 'imageURL_fields', f: builder %>
	  <% end %>
	  <%= link_to_add_fields "Add Image", f, :images %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_imageURL_fields.html.erb
<p>Type in product image URLS</p>
<fieldset class="image_urls">
     <%= f.text_field :title %>
 	 <%= f.text_field :imageURL %>
	 <%= link_to "remove", '#', class: "remove_fields" %>
	<%#= link_to_function "remove", "$(this).up('.image').remove()" %>
</fieldset>

app/views/products/_productLayout.html.erb
<div id='productBanner' class="banner">
	<div id='productTitle' class="bannerTitle">
		<h1>HIT Products & Services</h1>
	</div>
</div>

<div id='productContainer' class="contentContainer">
	<div id='productNav' class="contentNav">
		<ul>
   	 	<% @products.each do |product| %>
		<li><%= link_to product.title, product %></li>
		<% end %>
		</ul>
		
	</div>
	
	<div id='productContent' class="content">

app/views/products/all.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= render 'productLayout' %>

	<div id='productText'>
	
	<h3>Products & Services</h3>
	<p>HIT strives to deliver tangible solutions. HIT works continuously, both closely with partners or independently by utilizing its fully-equipped laboratory, in identifying rising challenges in industry and then designing, perfecting, and manufacturing technologies specifically tailored to address them. Following this mindset, HIT has an established history of successful products which it looks forward to extending. If you wish for more information on a certain technology that is not provided here or have inquiries about a possible future collaboration, please do not hesitate to <a href="mailto:info@holoimagetechnology.com">contact us</a>.  </p>
	</div> <!-- end #productText -->
	
	
</div> <!-- end #productContent -->
</div> <!-- end #productContainer -->

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%= render 'productLayout' %>


<h3>
  <%= @product.title %>
</h3>

<p>
  <%= markdown(@product.description) %>
</p>

<div class="productImgs">
	<%- @product.images.each do |img| %>
		<%#=image_tag "productImages/"+img.imageURL, :class => "productImages" %>
		<h4><%= img.title %></h4>
  	  	<%= link_to image_tag("productImages/"+img.imageURL, :class => "productImages" ), "../assets/productImages/"+img.imageURL %> </br >
  	<% end %>
</div>
	
</div> <!-- end #productContent -->
</div> <!-- end #productContainer -->